<?php

namespace MyGameBundle\Repository;

/**
 * BuildingProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingProcessRepository extends \Doctrine\ORM\EntityRepository
{
}
