<?php

namespace MyGameBundle\Repository;

/**
 * IslandBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IslandBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
