<?php

namespace MyGameBundle\Repository;

/**
 * IslandResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IslandResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
