<?php

namespace MyGameBundle\Repository;

/**
 * IslandTroopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IslandTroopRepository extends \Doctrine\ORM\EntityRepository
{
}
