<?php

namespace MyGameBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllMessages($id, $limit = null){
        return $this->getEntityManager()->createQuery(
            'SELECT m, s, r
            FROM MyGameBundle\Entity\Message m
            INNER JOIN m.sender s
            INNER JOIN m.receiver r
            WHERE s.id = :id OR r.id = :id
            ORDER BY m.sentOn ASC'
        )->setParameter('id', $id)->setMaxResults($limit)->getResult();
    }
}
