<?php

namespace MyGameBundle\Repository;

/**
 * TroopTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TroopTripRepository extends \Doctrine\ORM\EntityRepository
{
}
