<?php

namespace MyGameBundle\Repository;

/**
 * TroopCostResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TroopCostResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
