<?php

namespace MyGameBundle\Repository;

/**
 * TroopCostTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TroopCostTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
