<?php

namespace MyGameBundle\Repository;

/**
 * TroopProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TroopProcessRepository extends \Doctrine\ORM\EntityRepository
{
}
