<?php

namespace MyGameBundle\Repository;

/**
 * TroopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TroopRepository extends \Doctrine\ORM\EntityRepository
{
}
